### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by cetienn01** [cetienn01/cetienn01.github.io#19]
The background images are not displaying when i publish the site using GitHub pages.
The images display correctly when i test the website locally, but not on the live version.

**Comment by cetienn01** [comment]
## local view : 
<img width="1424" alt="Screen Shot 2020-07-30 at 5 06 48 PM" src="https://user-images.githubusercontent.com/46975293/88974819-36cc5480-d287-11ea-9df5-5f1768eb7a3e.png">

## live view : 
<img width="1434" alt="Screen Shot 2020-07-30 at 5 07 00 PM" src="https://user-images.githubusercontent.com/46975293/88974831-3cc23580-d287-11ea-8964-856ab90920d2.png">

**Comment by armish** [comment]
@cetienn01 It looks like you have a left-over trailing slash for the image URL:

https://github.com/cetienn01/cetienn01.github.io/search?q=home-bg-img.png&unscoped_q=home-bg-img.png

Removing that should fix your issue.

**Comment by cetienn01** [comment]
Thank you @armish, that fixed the display issue. 🙏🏿
